global:
  name: consul-blue
  domain: consul
  datacenter: dc-blue
  logLevel: "debug"
  image: "consul:1.12.2"
server:
  enabled: true
  replicas: 3
dns:
  enabled: true
ui:
  enabled: true
  service:
    type: 'NodePort'
connectInject:
  enabled: false
controller:
  enabled: false
client:
  enabled: false 
